#!/bin/bash

cd aospa # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
. build/envsetup.sh

export SELINUX_IGNORE_NEVERALLOWS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G
ccache -o compression=true
ccache -z

# stuffs
up(){
	curl --upload-file $1 https://transfer.sh/
}


}


                mka bacon -j16
		zip=$(up out/target/product/ysl/AOSPA*zip)
		echo " "
		echo "$zip"
}

./rom-build.sh ysl
curl -sL https://git.io/file-transfer | sh && ./transfer wet out/target/product/ysl/AOSP*
